# Data preparation

In [1]:
import pandas as pd
df = pd.read_csv("../dataset/online_shoppers_intention.csv")

df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [2]:
from sklearn.preprocessing import OrdinalEncoder
textual_columns = ['Month', 'VisitorType', 'Weekend', 'Revenue']
enc = OrdinalEncoder()
df[textual_columns] = enc.fit_transform(df[textual_columns])

df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2.0,1,1,1,1,2.0,0.0,0.0
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2.0,2,2,1,2,2.0,0.0,0.0
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,2.0,4,1,9,3,2.0,0.0,0.0
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,2.0,3,2,2,4,2.0,0.0,0.0
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,2.0,3,3,1,4,2.0,1.0,0.0

In [3]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['Revenue']), df['Revenue'], test_size=0.2, random_state=42)

print(f'Starting size: {df.shape}   =>  Training size: {x_train.shape} , Test size: {x_test.shape}')

Starting size: (12330, 18)   =>  Training size: (9864, 17) , Test size: (2466, 17)

In [4]:
from imblearn.over_sampling import SMOTENC

categorical_features = ['Month', 'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType', 'Weekend']
sm = SMOTENC(categorical_features=[c in categorical_features for c in df_train.columns])

x_train_resampled, y_train_resampled = sm.fit_resample(x_train, y_train)
# df_train_resampled = pd.concat((x_train_resampled, y_train_resampled), axis=1)

print(f'Starting size: {x_train.shape}   =>  Ovesampled Training size: {x_train_resampled.shape}')

NameError: name 'df_train' is not defined

In [33]:
from sklearn.preprocessing import StandardScaler

scl = StandardScaler()

x_train_scaled = scl.fit_transform(x_train_resampled)
x_test_scaled = scl.transform(x_test)

print('No change in dimension')

No change in dimension

In [34]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown='ignore')

In [36]:
x_train_scaled.shape

(16734, 17)

In [37]:
x_train

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
1785,0,0.000000,0,0.0,7,95.000000,0.014286,0.061905,0.000000,0.0,5.0,2,6,1,1,2.0,0.0
10407,2,14.000000,0,0.0,81,1441.910588,0.002469,0.013933,2.769599,0.0,7.0,2,2,3,2,2.0,0.0
286,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,5.0,2,2,1,1,2.0,0.0
6520,5,49.200000,4,379.0,5,74.600000,0.000000,0.018182,8.326728,0.0,9.0,2,2,8,2,0.0,0.0
12251,0,0.000000,1,5.0,9,279.000000,0.040000,0.041667,0.000000,0.0,7.0,3,2,7,8,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11964,14,1005.608333,0,0.0,25,732.344872,0.000000,0.015676,0.000000,0.0,7.0,3,2,1,2,2.0,0.0
5191,0,0.000000,0,0.0,14,340.000000,0.000000,0.015385,23.388000,0.0,6.0,2,2,3,1,2.0,1.0
5390,0,0.000000,0,0.0,3,189.000000,0.000000,0.066667,0.000000,0.0,6.0,2,2,3,4,2.0,0.0
860,0,0.000000,0,0.0,13,305.000000,0.000000,0.016667,0.000000,0.0,5.0,1,1,1,2,0.0,0.0
7270,7,138.150000,0,0.0,9,232.310000,0.000000,0.028718,0.000000,0.0,8.0,2,2,5,2,2.0,1.0

In [40]:
x_train_scaled[:, -1]

array([-0.44971273, -0.44971273, -0.44971273, ..., -0.44971273,
       -0.44971273, -0.44971273])